services:
  - type: web
    name: steam-app
    env: docker
    plan: free
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: 4000
      - key: DB_DATABASE
        value: steam
      - key: DB_USERNAME
        value: 3CkqCZNVEGSTaVc.root
      - key: DB_PASSWORD
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false